"""Los términos que se buscan en una oferta para saber qué está pidiendo.

Existe por una razón concreta: `criterio.py` sabe qué términos tenés vos —salen
de `busqueda.toml`— y con eso alcanza para ordenar ofertas, pero no para
contestar la pregunta que importa al momento de postular: *¿qué pide esta
oferta que mi CV no dice?* Para eso hace falta un vocabulario más ancho que el
propio, porque lo que no sabés no está en tu lista.

No pretende ser exhaustivo ni una ontología. Es lo que aparece en ofertas de
software y que un reclutador va a buscar en el CV; si falta algo que aparece
seguido, se agrega acá y no hay que tocar nada más.
"""

# Agrupado sólo para que sea legible y para que agregar uno sea obvio. El código
# los usa todos juntos.
_GRUPOS: dict[str, tuple[str, ...]] = {
    "lenguajes": (
        "python",
        "typescript",
        "javascript",
        "java",
        "c#",
        "golang",
        "rust",
        "ruby",
        "php",
        "kotlin",
        "swift",
        "scala",
        "elixir",
        "c++",
    ),
    "frontend": (
        "react",
        "next.js",
        "nextjs",
        "vue",
        "angular",
        "svelte",
        "remix",
        "tailwind",
        "redux",
        "react native",
        "expo",
        "flutter",
        "htmx",
    ),
    "backend": (
        "node.js",
        "nodejs",
        "express",
        "nestjs",
        "fastapi",
        "django",
        "flask",
        "spring",
        ".net",
        "asp.net",
        "rails",
        "laravel",
        "graphql",
        "grpc",
        "rest api",
        "microservices",
        "websockets",
        "sse",
    ),
    "datos": (
        "postgresql",
        "postgres",
        "mysql",
        "mongodb",
        "redis",
        "elasticsearch",
        "kafka",
        "rabbitmq",
        "snowflake",
        "bigquery",
        "dbt",
        "airflow",
        "sql server",
        "dynamodb",
        "supabase",
        "clickhouse",
    ),
    "ia": (
        "llm",
        "large language model",
        "rag",
        "retrieval augmented",
        "langchain",
        "langgraph",
        "llamaindex",
        "pgvector",
        "pinecone",
        "weaviate",
        "qdrant",
        "embeddings",
        "vector database",
        "fine-tuning",
        "prompt engineering",
        "openai",
        "anthropic",
        "claude",
        "gemini",
        "ollama",
        "hugging face",
        "pytorch",
        "tensorflow",
        "mcp",
        "model context protocol",
        "ai agent",
        "agentic",
        "evals",
        "machine learning",
        "nlp",
        "computer vision",
    ),
    "infra": (
        "aws",
        "gcp",
        "azure",
        "docker",
        "kubernetes",
        "terraform",
        "ansible",
        "ci/cd",
        "github actions",
        "jenkins",
        "vercel",
        "railway",
        "cloudflare",
        "serverless",
        "lambda",
        "observability",
        "datadog",
        "prometheus",
        "grafana",
        "linux",
    ),
    "practicas": (
        "tdd",
        "unit testing",
        "integration testing",
        "code review",
        "agile",
        "scrum",
        "kanban",
        "pair programming",
        "system design",
        "architecture",
        "mentoring",
        "technical writing",
        "on-call",
        "incident response",
        "security",
        "owasp",
        "authentication",
        "oauth",
        "jwt",
    ),
    "negocio": (
        "fintech",
        "healthtech",
        "e-commerce",
        "saas",
        "b2b",
        "b2c",
        "startup",
        "marketplace",
        "payments",
        "compliance",
        "hipaa",
        "soc 2",
        "gdpr",
    ),
}

TERMINOS: tuple[str, ...] = tuple(
    sorted({termino for grupo in _GRUPOS.values() for termino in grupo})
)
